name: Deploy ashu-ec2vpc-day33

on:
  push:
    branches:
      - mainnnnnnn

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: | 
        npm install
        npm install -g aws-cdk
      working-directory: ./ashu-ec2vpc-day33

    - name: deploy cdk in aws account 
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        cd ashu-ec2vpc-day33/
        cdk deploy  --require-approval never